### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MaxSchouten** [GunsAkimbo/autodl-chatzilla#1]
Would it be possible to automatically add a label to everything thats uploaded through utorrent webui?

**Comment by GunsAkimbo** [comment]
This is already possible with the script option and I have been using it for a long time already. See attached pic. If you want to have a fixed value, replace $(Category) with something else.
![skjermbilde 2014-08-07 kl 11 11 26](https://cloud.githubusercontent.com/assets/1919936/3839549/64564828-1e12-11e4-9163-cbf4dd91dd49.png)

**Comment by MaxSchouten** [comment]
Thanks for the wicked fast response. Does the category take the label name from the filters settings?

**Comment by GunsAkimbo** [comment]
Not directly from filter settings, but parsed from the IRC announce text if the bot writes it. The label name will basically be the same name as torrent category name :)

Edit: clarification

**Comment by MaxSchouten** [comment]
Ah, thats genius! I'm only using it for tv series so i'll just stick with the fixed value method. Thnx!

**Comment by MaxSchouten** [comment]
Messing with the script section a bit, it's also possible to have it extract archives and move the extracted content to another folder? I currently have a python script in utorrent to do just that, however it extracts everything that gets downloaded, not just tv episodes (which kind of sucks). 

Whenever I click the browse button in ChatZilla, it throws up this error "Could not browse for file/folder. Error: TypeError: netscape.security.PrivilegeManager is undefined". Do you know a way to fix this? (im running it in firefox, not XUL)

**Comment by MaxSchouten** [comment]
Just downgraded to ChatZilla v0.9.86 and went the XUL way, browsing folders now works perfectly! Any suggestions on the unpacking part? Should I just leave it blank, select my download folder, or use some other argument? This is how I set it up: 
![image](https://cloud.githubusercontent.com/assets/8152340/3840808/2f7320ac-1e23-11e4-8dc5-030bc2b1fdef.png)

**Comment by GunsAkimbo** [comment]
Mozilla removed the support for netscape.security.PrivilegeManager in FF 17, it seems: https://bugzilla.mozilla.org/show_bug.cgi?id=546848

Can't really help you with the unpacking, I have not used it other than the webui part.

The purpose of this repository was just to fix some critical bugs only, because I was tired of living in constant fear for Firefox updating my Chatzilla to 0.9.90 which broke the plugin :P I am not really using chatzilla-autodl anymore, as I have moved on to irssi-autodl for rTorrent/ruTorrent.

**Comment by MaxSchouten** [comment]
Ah, too bad. I can't run linux on my primary pc, so i'll have to stick with ChatZilla. Thanks for all the help!
